package checkedException;

import checkedException.division.Operations;
import java.util.Scanner;

//This example implements an exception for when a number is divided by zero
//Input: 2 numbers
//output: division
public class Main {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);

        System.out.print("Ingrese el primer numero: ");
        Double a =input.nextDouble();
        System.out.print("Ingrese el segundo numero: ");
        Double b = input.nextDouble();

        //use of try-catch to handle the exception generated by the function (division)
        try{
            Double result = Operations.division(a,b);
            System.out.printf("Resultado: %.1f",result);
        }catch (Exception ex){
            System.out.println("No se puede dividir por cero");
        }

    }
}
